# CMU 16-726 Learning-Based Image Synthesis / Spring 2024, Assignment 3
#
# The code base is based on the great work from CSC 321, U Toronto
# https://www.cs.toronto.edu/~rgrosse/courses/csc321_2018/assignments/a4-code.zip
# This is the main training file for the second part of the assignment.
#
# Usage:
# ======
#    To train with the default hyperparamters:
#       python cycle_gan.py
#
#    To train with cycle consistency loss:
#       python cycle_gan.py --use_cycle_consistency_loss
#
#
#    For optional experimentation:
#    -----------------------------
#    If you have a powerful computer (ideally with a GPU),
#    then you can obtain better results by
#    increasing the number of filters used in the generator
#    and/or discriminator, as follows:
#      python cycle_gan.py --g_conv_dim=64 --d_conv_dim=64

import argparse
import os

import imageio
from torch.utils.tensorboard import SummaryWriter
import torch
import torch.optim as optim
import numpy as np

import utils
from data_loader import get_data_loader
from models import CycleGenerator, DCDiscriminator, PatchDiscriminator
from diff_augment import DiffAugment
policy = 'color,translation,cutout'


SEED = 11

# Set the random seed manually for reproducibility.
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)


def print_models(G, D, style_iden):
    """Prints model information for the generators and discriminators.
    """
    print("                 G                ")
    print("---------------------------------------")
    print(G)
    print("---------------------------------------")

    print("                 D                ")
    print("---------------------------------------")
    print(D)
    print("---------------------------------------")

    print("                  style_identifier                  ")
    print("---------------------------------------")
    print(style_iden)
    print("---------------------------------------")


def create_model(opts):
    """Builds the generators and discriminators.
    """
    model_dict = {'cycle': CycleGenerator}
    G = model_dict[opts.gen](conv_dim=opts.g_conv_dim, norm=opts.norm) 

    model_dict = {'dc': DCDiscriminator, 'patch': PatchDiscriminator}
    D = model_dict[opts.disc](conv_dim=opts.d_conv_dim, norm=opts.norm) 

    style_iden = model_dict[opts.style_iden](conv_dim=opts.d_conv_dim, norm=opts.norm) 

    
    print_models(G, D, style_iden)

    if torch.cuda.is_available():
        G.cuda()
        D.cuda()
        style_iden.cuda() 
        print('Models moved to GPU.')

    return G, D, style_iden


def checkpoint(iteration, G, D, g_optimizer, d_optimizer, opts):
    """Save generators G_YtoX, G_XtoY and discriminators D_X, D_Y."""
    G_path = os.path.join(
        opts.checkpoint_dir, '%ditr/G.pkl' % iteration
    )
    D_path = os.path.join(
        opts.checkpoint_dir, '%ditr/D.pkl' % iteration
    ) 
    g_opt_path = os.path.join(opts.checkpoint_dir, '%ditr/g_optimizer.pkl' % iteration)
    d_opt_path = os.path.join(opts.checkpoint_dir, '%ditr/d_optimizer.pkl' % iteration)
    
    torch.save(G.state_dict(), G_path)
    torch.save(D.state_dict(), D_path) 
    torch.save(g_optimizer.state_dict(), g_opt_path)
    torch.save(d_optimizer.state_dict(), d_opt_path)

# THIS NEEDS EDITING
# have 2 ppl images, have them try on all other 30 hair styles
def merge_images(sources, targets, opts, k=10):
    """
    Creates a grid consisting of pairs of columns, where the first column in
    each pair contains images source images and the second column in each pair
    contains images generated by the CycleGAN from the corresponding images in
    the first column.
    """
    _, _, h, w = sources.shape
    row = int(np.sqrt(opts.batch_size))
    merged = np.zeros([3, row * h, row * w * 2])
    for idx, (s, t) in enumerate(zip(sources, targets)):
        i = idx // row
        j = idx % row
        merged[:, i * h:(i + 1) * h, (j * 2) * h:(j * 2 + 1) * h] = s
        merged[:, i * h:(i + 1) * h, (j * 2 + 1) * h:(j * 2 + 2) * h] = t
    return merged.transpose(1, 2, 0)

# have 2 ppl images, have them try on all other 30 hair styles
def save_samples(iteration,fixed_X, G, opts):
    """Saves samples from both generators X->Y and Y->X.
    """
    new_X = G(fixed_X)
    # fake_Y = G_XtoY(fixed_X)

    X, fake_X = utils.to_data(fixed_X), utils.to_data(new_X)
    # Y, fake_Y = utils.to_data(fixed_Y), utils.to_data(fake_Y)

    merged = merge_images(X, fake_X, opts)
    path = os.path.join(
        opts.sample_dir, 'sample-{:06d}-X-Y.png'.format(iteration)
    )
    merged = np.uint8(255 * (merged + 1) / 2)
    imageio.imwrite(path, merged)
    print('Saved {}'.format(path))


def training_loop(dataloader_X, validation_loader, opts):
    """Runs the training loop.
        * Saves checkpoint every opts.checkpoint_every iterations
        * Saves generated samples every opts.sample_every iterations
    """
    # Create generators and discriminators
    G, D, style_iden = create_model(opts)

    g_params = list(G.parameters())  
    d_params = list(D.parameters()) 

    # Create optimizers for the generators and discriminators
    g_optimizer = optim.Adam(g_params, opts.lr, [opts.beta1, opts.beta2])
    d_optimizer = optim.Adam(d_params, opts.lr, [opts.beta1, opts.beta2])

    iter_X = iter(dataloader_X) 
    iter_per_epoch =len(dataloader_X)

    # Get some fixed data from domains X and Y for sampling.
    # These are images that are held constant throughout training,
    # that allow us to inspect the model's performance.
    fixed_X = utils.to_var(next(iter_X)) 

    for iteration in range(1, opts.train_iters + 1):

        # Reset data_iter for each epoch
        if iteration % iter_per_epoch == 0:
            iter_X = iter(dataloader_X) 

        images = next(iter_X) 
        images,labels = (utils.to_var(images[0]), utils.to_var(images[1]))  

        # TRAIN THE DISCRIMINATORS
        # 1. Compute the discriminator losses on real images
        d_real_loss = torch.mean((D(images) - 1) ** 2) 

        # 2. Generate domain-X-like images based on real images in domain Y
        fake_images = G(images,labels)

        # 3. Compute the loss for D_X
        d_fake_loss = torch.mean((D(fake_images))**2) 

        # sum up the losses and update D_X and D_Y
        d_optimizer.zero_grad()
        d_total_loss = d_real_loss + d_fake_loss
        d_total_loss.backward()
        d_optimizer.step()

        # plot the losses in tensorboard
        logger.add_scalar('D/real', d_real_loss, iteration)
        logger.add_scalar('D/fake', d_fake_loss, iteration)

        # TRAIN THE GENERATORS
        
        # 1. Creating inputs for the generator
        # Repeat each image 30 times (31 styles, want to try other 30)
        images_expanded = images.unsqueeze(1).repeat(1, 30, 1, 1, 1)  # (batch_size, num_styles, C, H, W)
        images_expanded = images_expanded.view(-1, *images.shape[1:])  # (batch_size * num_styles, C, H, W)
        
        # create new style vectors for each image
        new_style_indices = utils.to_var(torch.arange(31)).repeat(opts.batch_size)  # (batch_size * num_styles,) 
        new_labels = torch.nn.functional.one_hot(new_style_indices, 31).float()

        # original labels same shape as num_styles, with ground truth
        orig_labels = labels.unsqueeze(1).repeat(1, 30).view(-1)  # (batch_size * num_styles,) 
        orig_labels = torch.nn.functional.one_hot(orig_labels, num_classes=30).float()  

        # 2. Generate fake images based on real images
        fake_images = G(images,new_labels)

        # 3. Compute the generator loss based on domain X
        g_loss = torch.mean((D(fake_images)-1)**2)
        logger.add_scalar('G/fake', g_loss, iteration)

        if opts.use_cycle_consistency_loss:
            # 4. Compute the cycle consistency loss (the reconstruction loss)
            cycle_consistency_loss = torch.mean(torch.abs(images - G(fake_images,orig_labels)))

            g_loss += opts.lambda_cycle * cycle_consistency_loss
            logger.add_scalar('G/cycle', opts.lambda_cycle * cycle_consistency_loss, iteration)
        
        if opts.use_style_loss:
            # 5. Compute the style loss (style alignment loss)
            with torch.no_grad():
                style_loss = torch.mean(torch.abs(orig_labels - style_iden(fake_images)))

            g_loss += opts.lambda_style * style_loss
            logger.add_scalar('G/style', opts.lambda_style * style_loss, iteration)

        # backprop the aggregated g losses and update G_XtoY and G_YtoX
        g_optimizer.zero_grad()
        g_loss.backward()
        g_optimizer.step()

        # Print the log info
        if iteration % opts.log_step == 0:
            print(
                'Iteration [{:5d}/{:5d}] | d_real_loss: {:6.4f} | '
                'd_fake_loss: {:6.4f} | d_total_loss: {:6.4f} |  g_loss: {:6.4f}'.format(
                    iteration, opts.train_iters, d_real_loss.item(),
                    d_fake_loss.item(), d_total_loss.item(), g_loss.item()
                )
            )
            G.eval()
            D.eval()
            with torch.no_grad():
                val_d_loss_total = 0.0
                val_g_loss_total = 0.0
                val_batches = 0
        
                for val_images, val_labels in validationloader:
                    val_images = utils.to_var(val_images)
                    val_labels = utils.to_var(val_labels)
        
                    # Discriminator loss on validation
                    val_fake_images = G(val_images, val_labels)
                    val_d_real = torch.mean((D(val_images) - 1) ** 2)
                    val_d_fake = torch.mean((D(val_fake_images)) ** 2)
                    val_d_loss = val_d_real + val_d_fake
        
                    # Generator loss on validation
                    val_g_loss = torch.mean((D(val_fake_images) - 1) ** 2)
        
                    val_d_loss_total += val_d_loss.item()
                    val_g_loss_total += val_g_loss.item()
                    val_batches += 1
        
                avg_val_d_loss = val_d_loss_total / val_batches
                avg_val_g_loss = val_g_loss_total / val_batches
        
                print('Validation | d_loss: {:6.4f} | g_loss: {:6.4f}'.format(avg_val_d_loss, avg_val_g_loss))
            G.train()
            D.train()
            

        # Save the generated samples
        if iteration % opts.sample_every == 0:
            save_samples(iteration, fixed_X, G, opts)

        # Save the model parameters
        if iteration % opts.checkpoint_every == 0: 
            checkpoint(iteration, G, D, g_optimizer, d_optimizer, opts)


def main(opts):
    """Loads the data and starts the training loop."""
    # Create  dataloaders for images from the two domains X and Y
    dataloader_X, validation_loader = get_data_loader(opts.X, opts=opts) 

    # Create checkpoint and sample directories
    utils.create_dir(opts.checkpoint_dir)
    utils.create_dir(opts.sample_dir)

    # Start training
    training_loop(dataloader_X, validation_loader, opts)


def print_opts(opts):
    """Prints the values of all command-line arguments.
    """
    print('=' * 80)
    print('Opts'.center(80))
    print('-' * 80)
    for key in opts.__dict__:
        if opts.__dict__[key]:
            print('{:>30}: {:<30}'.format(key, opts.__dict__[key]).center(80))
    print('=' * 80)


def create_parser():
    """Creates a parser for command-line arguments.
    """
    parser = argparse.ArgumentParser()

    # Model hyper-parameters
    parser.add_argument('--image_size', type=int, default=64)
    parser.add_argument('--disc', type=str, default='dc')  # or 'patch'
    parser.add_argument('--gen', type=str, default='cycle')
    parser.add_argument('--g_conv_dim', type=int, default=32)
    parser.add_argument('--d_conv_dim', type=int, default=32)
    parser.add_argument('--norm', type=str, default='instance')
    parser.add_argument('--use_cycle_consistency_loss', action='store_true')
    parser.add_argument('--init_zero_weights', action='store_true')
    parser.add_argument('--init_type', type=str, default='naive')

    # Training hyper-parameters
    parser.add_argument('--train_iters', type=int, default=10000)
    parser.add_argument('--batch_size', type=int, default=16)
    parser.add_argument('--num_workers', type=int, default=2)
    parser.add_argument('--lr', type=float, default=0.0003)
    parser.add_argument('--beta1', type=float, default=0.5)
    parser.add_argument('--beta2', type=float, default=0.999)
    parser.add_argument('--lambda_cycle', type=float, default=10)
    parser.add_argument('--lambda_style', type=float, default=10)

    # Data sources
    parser.add_argument('--X', type=str, default='cat/grumpifyAprocessed')
    parser.add_argument('--Y', type=str, default='cat/grumpifyBprocessed')
    parser.add_argument('--ext', type=str, default='*.png')
    parser.add_argument('--use_diffaug', action='store_true')
    parser.add_argument('--data_preprocess', type=str, default='vanilla')

    # Saving directories and checkpoint/sample iterations
    parser.add_argument('--checkpoint_dir', default='checkpoints_cyclegan')
    parser.add_argument('--sample_dir', type=str, default='cyclegan')
    parser.add_argument('--log_step', type=int, default=10)
    parser.add_argument('--sample_every', type=int, default=100)
    parser.add_argument('--checkpoint_every', type=int, default=800)

    parser.add_argument('--gpu', type=str, default='0')

    return parser


if __name__ == '__main__':
    parser = create_parser()
    opts = parser.parse_args()
    os.environ['CUDA_VISIBLE_DEVICES'] = opts.gpu
    opts.sample_dir = os.path.join(
        'output/', opts.sample_dir,
        '%s_%g' % (opts.X.split('/')[0], opts.lambda_cycle)
    )
    opts.sample_dir += '%s_%s_%s_%s_%s' % (
        opts.data_preprocess, opts.norm, opts.disc, opts.gen, opts.init_type
    )
    if opts.use_cycle_consistency_loss:
        opts.sample_dir += '_cycle'
    if opts.use_diffaug:
        opts.sample_dir += '_diffaug'

    if os.path.exists(opts.sample_dir):
        cmd = 'rm %s/*' % opts.sample_dir
        os.system(cmd)

    logger = SummaryWriter(opts.sample_dir)

    print_opts(opts)
    main(opts)
